# Site settings
title: Valentina Garcia Ovies Portfolio
description: Personal portfolio for business and data analytics.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Valentina Garcia Ovies
user_description: Bienvenidos! I’m a business analytics graduate with a background in finance and international Business. Over the past couple of years, I’ve developed key skills through hands-on projects, some showcased here, others that quietly shaped my journey. 
  Born and raised in Colombia, I carry with me a deep passion for growth and perseverance. Moving to the U.S. taught me the value of continuous learning, and I’m excited to keep expanding my skills in data analytics, both through new tools and by learning from others. Thank you for stopping by!
user_title: Business Analyst
email: garciaoviesvalentina@gmail.com
tableau_username: lorem_ipsum
github_username:  lorem_ipsum
linkedin_username:  lorem_ipsum
personal_description: Life is full of blessings and some things I enjoy in life outside of work are dancing (truly anything but I cannot say no to a good salsa class), playing tennis (the means to come to the US so I can't
 really leave it fully), trying new foods and traveling (these two go hand and hand).

# Google-analytics
google-analytics:
  id: "10605593963"


exclude: ['package.json', 'src' , 'node_modules']
