# Site settings
title: Valentina Garcia Ovies Portfolio
description: Personal portfolio for business and data analytics.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Valentina Garcia Ovies
user_description: Business analytics master student graduate with an undergraduate background in finance and international business. Within the last two years, my experience and knowledge has grown by developing skills in Tableau, Excel, SQL, and power BI.
                  Being born and raised in Colombia and coming to the US has taught me to keep looking and moving forward. A way I do this is by contstantly keep learning. I plan to continue advancing my skills in this field not just by learning other skills like Python and deepening my skills but also learning from other experts. Thank you for the opportunity.
user_title: Business Analyst
email: garciaoviesvalentina@gmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "10605593963"


exclude: ['package.json', 'src' , 'node_modules']
